### ISSUE TITLE
Doesent seem to work

### ISSUE THREAD

**Issue by valzzu** [MineTech13/homeassistant-basestation#1]
i set this up as was shown but the switches don't show up, only the group does.

**Comment by valzzu** [comment]
nvm, idk what i did but now it works.

**Comment by systemofapwne** [comment]
What was your solution?
I am in the same situation. My basestations can bee seen by my ESP32 bluetooth proxies:

![Image](https://github.com/user-attachments/assets/acab1bf2-fe75-48cd-9dc4-a1b3ca455f0d)

The integration has been added via HACS and I configured my basestations according to the readme.

/config/include/switch
```yaml
- name: "wohnzimmer_schrank_lhb"
  platform: basestation
  mac: "EA:3C:98:79:E5:7F"

- name: "wohnzimmer_fenster_lhb"
  platform: basestation
  mac: "FC:4B:67:DF:AD:62"
```

and `configuration.yaml` is including it
```yaml
#... other code
switch: !include_dir_merge_named include/switch/
#... other code
```

It makes no difference, if I directly configure it via the `configuration.yaml` or include it via `!include_dir_merge_named`. The basestations simply wont show up.
